feat(auth): add postman automatic oauth
Compairifuel/Compairifuel pull request #108
Opened 2024-12-03 13:54 UTC by Mino03947

2024-12-13 07:09 UTC, JaronZ requested changes

2024-12-19 15:00 UTC, Mino03947 commented on compairifuel-api/src/main/java/org/compairifuel/compairifuelapi/authorization/service/AuthorizationServiceImpl.java
> +        if (!Arrays.equals(Base64.getUrlDecoder().decode(claims.get("code_challenge", String.class)), DigestUtils.sha256(codeVerifier))) {
No it isn't. Line 108 also contains a redirectUri condition. But It won't have much effect to make 1 line into a function. And in my opinion it's readable.

2024-12-21 13:41 UTC, JaronZ approved these changes

2024-12-30 17:11 UTC, JaronZ approved these changes

2025-01-09 12:11 UTC, Mino03947 commented on compairifuel-api/.gitignore
> +whitelisted_uri.yml
I don't think this is working.

2025-01-09 12:11 UTC, Mino03947 commented on compairifuel-api/src/main/java/org/compairifuel/compairifuelapi/authorization/service/AuthorizationServiceImpl.java
> +                throw new ForbiddenException();
I don't think this line of code works as intended.

2025-01-09 12:48 UTC, altergith approved these changes

2025-01-20 19:07 UTC, JaronZ commented on compairifuel-api/src/main/java/org/compairifuel/compairifuelapi/authorization/service/AuthorizationServiceImpl.java
> +import java.io.BufferedReader;
I don't see any reason for this change. It removes 2 lines of code and imports more than necessary.

2025-01-21 08:26 UTC, Mino03947 commented on compairifuel-api/src/main/java/org/compairifuel/compairifuelapi/authorization/service/AuthorizationServiceImpl.java
> +import java.io.BufferedReader;
Yes, good call.

2025-01-29 12:26 UTC, merged