feat(test): add unit and widget tests
Compairifuel/Compairifuel pull request #95
Opened 2024-11-22 15:53 UTC by Mino03947

2024-11-27 20:22 UTC, JaronZ requested changes
The only thing I saw was how hashCode is calculated. The code looks good other than that.

2024-11-28 13:09 UTC, JaronZ approved these changes
Looks good to me

2024-11-28 19:03 UTC, altergith approved these changes
Ziet er netjes uit, alleen nog wat kleine punten en vraagjes.

2024-11-29 08:50 UTC, Mino03947 commented on compairifuel/test/models/access_token_test.dart
> +      expect(result.hashCode, equals(expected.hashCode));
The difference, lies in the hashcode, the hashcode is an extra check to know if the result is the exact same object. It is also necessary to increase the amount of test coverage. A hashcode can return false, while equals can return true.

I increased readability for you in the changes.

2024-11-29 20:29 UTC, altergith approved these changes
Looks good, well done

2024-11-29 20:30 UTC, merged